global:
  resolve_timeout: 30m

  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: "${GMAIL_SENDER}"
  smtp_auth_username: "${GMAIL_SENDER}"
  smtp_auth_password: "${GMAIL_APP_PASSWORD}"
  smtp_require_tls: true

route:
  group_by: ['alertname', 'env']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  receiver: 'default'
  routes:
    - match:
        severity: warning
      receiver: 'default'
    - match:
        severity: critical
      receiver: 'default'

receivers:
  - name: 'default'
    email_configs:
      - to: "${GMAIL_RECEIVER}"
        send_resolved: true 

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'instance']
