global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

  external_labels:
    environment: 'production'


rule_files:
  - "rules/*.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  
  - job_name: 'host-node-exporter'
    static_configs:
      - targets: ['host-node-exporter:9100']

  - job_name: 'workflow-app'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['workflow-app:3000']
